---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
spec:
  type: ClusterIP
  ports:
  - name: {{ .Values.app }}
    port: 4567
    targetPort: 4567
    protocol: TCP
  selector:
    app: {{ .Values.app }}
