name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.6

    - name: Setup System
      run: |
        sudo apt-get update

    - name: Gem Cache
      id: gem-cache
      uses: actions/cache@v1
      with:
        path: ~/.gem
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          ${{ runner.os }}-gem-

    - name: Update Gem cache
      if: steps.gem-cache.outputs.cache-hit != 'true'
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Lint Ruby, standardrb
      run: |
        gem install standardrb
        bundle exec standardrb app

    - name: erb linting
      run: |
        gem install erb_lint
        bundle exec erblint views/*

    - name: Running tests
      run: |
        gem install rspec
        bundle exec rspec
